# Application Build
FROM rust:latest as build
ENV USER=root

RUN rustup target add x86_64-unknown-linux-musl

RUN set -eux; \
    apt-get update; \
    apt-get install -y --no-install-recommends \
        musl-tools \
    ; \
    rm -rf /var/lib/apt/lists/*;

WORKDIR /app
COPY . /app/

RUN cargo build --release --target=x86_64-unknown-linux-musl
RUN strip target/x86_64-unknown-linux-musl/release/kafka-bridge

# Runtime Build
FROM alpine:latest

RUN apk --no-cache add tini
RUN addgroup -g 1000 appuser
RUN adduser -S -u 1000 -g appuser -G appuser appuser
USER appuser

WORKDIR /app
COPY --from=build /app/target/x86_64-unknown-linux-musl/release/kafka-bridge /app

# Setup the environment
ENTRYPOINT ["/sbin/tini", "--"]

# Runtime
ENV RUST_BACKTRACE=1
CMD ["/app/kafka-bridge"]
